name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0 # Must be aligned with 'flutter:'
  geolocator: ^13.0.0
  cupertino_icons: ^1.0.8 # Must be aligned with 'flutter:'
  supabase_flutter: ^2.8.0
  http: ^1.1.0
  image_picker: ^0.8.7+4
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
